name: "update"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        uses: devcontainers/ci@v0.2
        with:
          push: always
          imageName: ghcr.io/rails-lambda/lamby-cookiecutter-devcontainer
          cacheFrom: ghcr.io/rails-lambda/lamby-cookiecutter-devcontainer
          runCmd: |
            ./bin/build
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto Update
